server:
  port: ${port:8088}

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tosintubi/environment-variable-repo.git

